name: macOS CI

# Workflow syntax.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - '*'

env:
  PACKAGE_NAME: aws-lc
  # Used to enable ASAN test dimension.
  AWSLC_NO_ASM_FIPS: 1

jobs:
  macOS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }}
      run: |
        ./tests/ci/run_posix_tests.sh

  macOS-FIPS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }} with FIPS mode
      run: |
        ./tests/ci/run_fips_tests.sh

  macOS-arm:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
    - name: Build ${{ env.PACKAGE_NAME }}
      run: |
        ./tests/ci/run_posix_tests.sh

  macOS-arm-FIPS:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
    - name: Build ${{ env.PACKAGE_NAME }} with FIPS mode
      run: |
        ./tests/ci/run_fips_tests.sh